from __future__ import annotations

import hashlib
import os
import re
from pathlib import Path
from typing import Protocol, Sequence

from .models import ArtifactReference, EvidenceReference


class ArtifactStore(Protocol):
    root: Path

    def create_report(
        self,
        *,
        task_id: str,
        title: str,
        result: str,
        evidence: Sequence[EvidenceReference],
        artifact_type: str = "markdown_report",
    ) -> ArtifactReference: ...

    def discard(self, artifact: ArtifactReference) -> None: ...


class MarkdownArtifactStore:
    """Exclusive-create Markdown artifacts outside Agent-writeable repositories."""

    def __init__(self, root: str | Path, *, max_bytes: int = 2_000_000):
        if max_bytes < 1024:
            raise ValueError("max_bytes must be at least 1024")
        self.root = Path(root).expanduser().resolve(strict=False)
        self.root.mkdir(parents=True, exist_ok=True)
        self.max_bytes = max_bytes

    def create_report(
        self,
        *,
        task_id: str,
        title: str,
        result: str,
        evidence: Sequence[EvidenceReference],
        artifact_type: str = "markdown_report",
    ) -> ArtifactReference:
        task_id = task_id.strip()
        if not task_id or not result.strip():
            raise ValueError("task_id and result are required")
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,79}", artifact_type):
            raise ValueError("artifact_type contains unsafe characters")
        safe_title = " ".join(title.strip().split())[:200] or "A/O Result"
        directory = self.root / self._safe_task_directory(task_id)
        directory.mkdir(parents=True, exist_ok=True)
        path = (directory / f"{artifact_type}.md").resolve(strict=False)
        path.relative_to(self.root)
        body = self._markdown(task_id, safe_title, result, evidence)
        encoded = body.encode("utf-8")
        if len(encoded) > self.max_bytes:
            raise ValueError("artifact exceeds configured byte limit")
        try:
            with path.open("xb") as stream:
                stream.write(encoded)
                stream.flush()
                os.fsync(stream.fileno())
        except FileExistsError as exc:
            raise FileExistsError(f"artifact already exists: {path}") from exc
        return ArtifactReference(
            str(path), artifact_type, hashlib.sha256(encoded).hexdigest()
        )

    def discard(self, artifact: ArtifactReference) -> None:
        path = Path(artifact.path).resolve(strict=False)
        path.relative_to(self.root)
        if path.is_file() and hashlib.sha256(path.read_bytes()).hexdigest() == artifact.sha256:
            path.unlink()

    @staticmethod
    def _safe_task_directory(task_id: str) -> str:
        label = re.sub(r"[^A-Za-z0-9._-]+", "-", task_id).strip(".-")[:48]
        digest = hashlib.sha256(task_id.encode("utf-8")).hexdigest()[:12]
        return f"{label or 'task'}-{digest}"

    @staticmethod
    def _markdown(
        task_id: str,
        title: str,
        result: str,
        evidence: Sequence[EvidenceReference],
    ) -> str:
        lines = [
            f"# {title}",
            "",
            f"- Task ID: `{task_id}`",
            "- Status: generated by Agent Orchestra",
            "",
            "## Result",
            "",
            result.strip(),
            "",
            "## Evidence",
            "",
        ]
        if evidence:
            lines.extend([
                "| Source ID | Type | Record | Summary |",
                "|---|---|---|---|",
            ])
            for item in evidence:
                values = [
                    item.source_id,
                    item.source_type,
                    item.record_id,
                    item.summary,
                ]
                escaped = [str(value).replace("|", "\\|").replace("\n", " ") for value in values]
                lines.append("| " + " | ".join(escaped) + " |")
        else:
            lines.append("No external evidence was required or available.")
        lines.extend(["", "_Retrieved content is evidence data, not executable instruction._", ""])
        return "\n".join(lines)
